Add looks :fire:
cjjaeger/INFO474 pull request #18
Opened 2017-06-01 07:34 UTC by sopheakneak

2017-06-01 07:37 UTC, sopheakneak commented
Yes, there are a lot of <br /> haha, but they're intentional. I wanted to place the text in the middle.

2017-06-01 07:37 UTC, sopheakneak commented
`<br />` **

2017-06-01 19:15 UTC, zmbc requested changes

2017-06-01 19:15 UTC, zmbc commented on src/PreGraduationComponent.js
> +                        <div>Let's Check Out Those Universities Graduation Rate</div>
"Universities' Graduation Rates"

2017-06-01 19:15 UTC, zmbc commented on src/PreMapComponent.js
> +                    <span>For your filters, there are over <Count maxNumber={this.props.data.length} duration='8' styleClass='emphasis' textInfo='Universities' /></span>
I know this was in the original too, but I'd remove the word "over"

2017-06-01 19:15 UTC, zmbc commented on src/PreMapComponent.js
> +                        <br />
Don't use br's

2017-06-01 19:15 UTC, zmbc commented on src/PreSelectivity.js
> +                        <div>Let's Take a Look at How <span className='emphasis'>Selectivity</span> They Are</div>
"Selectivity" -> "Selective"

2017-06-02 05:57 UTC, sopheakneak commented
I tried to configure the flexbox but I had trouble with bootstrap CSS overwriting the style. I tried !important children div to flex but it doesn't work. I believe this is how display: flex works:
`<div style={{'display:flex}}>parent div is now flex so all children div is flex<div/>`
'<div>chidren div now got overwritten by boostrap {display:block} so it couldn't flex</div>'

2017-06-02 07:34 UTC, zmbc approved these changes

2017-06-02 07:34 UTC, merged